<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:property name="motor_wheel_diameter" value="0.050"/>
    <xacro:property name="motor_wheel_width" value="0.020"/>
    <xacro:property name="motor_wheel_separation" value="0.114"/> <!--center to center-->

    <xacro:property name="encoder_wheel_diameter" value="0.050"/>
    <xacro:property name="encoder_wheel_width" value="0.005"/>
    <xacro:property name="encoder_wheel_separation" value="0.142"/> <!--center to center-->

    <xacro:property name="chassis_base_height" value="0.065"/>
    <xacro:property name="chassis_width" value="0.200"/>
    <xacro:property name="chassis_length" value="0.200"/>
    <xacro:property name="chassis_height" value="0.056"/>


    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="grey">
        <color rgba="0.2 0.2 0.2 1"/>
    </material>

    <material name="brown">
        <color rgba="0.5 0.2 0 1"/>
    </material>

    <link name="base_link"></link>

    <joint name="synthetic_mass_joint" type="fixed">
        <parent link="base_link"/>
        <child link="synthetic_mass"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="synthetic_mass">
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0.0 0.0 0.025" rpy="0.0 0.0 0.0"/>
            <inertia ixx="0.0007" ixy="0.0" ixz="0.0" iyy="0.0007" iyz="0.0" izz="0.0008"/>
        </inertial>
    </link>

    <!-- CHASSIS -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${chassis_base_height - motor_wheel_diameter/2 + chassis_height/2}"/>
    </joint>


    <link name="chassis">
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
                <material name="brown"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
    </link>

    <!-- MOTOR WHEELS -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="motor_left_wheel"/>
        <origin xyz="0 ${motor_wheel_separation/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="motor_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${motor_wheel_diameter/2}" length="${motor_wheel_width/2}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${motor_wheel_diameter/2}" length="${motor_wheel_width/2}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0.0 0.0 0.025" rpy="0.0 0.0 0.0"/>
            <inertia ixx="0.00007" ixy="0.0" ixz="0.0" iyy="0.00007" iyz="0.0" izz="0.00008"/>
        </inertial>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="motor_right_wheel"/>
        <origin xyz="0 -${motor_wheel_separation/2} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="motor_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${motor_wheel_diameter/2}" length="${motor_wheel_width/2}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${motor_wheel_diameter/2}" length="${motor_wheel_width/2}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0.0 0.0 0.025" rpy="0.0 0.0 0.0"/>
            <inertia ixx="0.00007" ixy="0.0" ixz="0.0" iyy="0.00007" iyz="0.0" izz="0.00008"/>
        </inertial>
    </link>

     <!-- ENCODER WHEELS -->

    <joint name="encoder_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="encoder_left_wheel"/>
        <origin xyz="0 ${encoder_wheel_separation/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="encoder_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${encoder_wheel_diameter/2}" length="${encoder_wheel_width/2}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <inertial>
            <mass value="0.01"/>
            <inertia ixx="0.000007" ixy="0.0" ixz="0.0" iyy="0.000007" iyz="0.0" izz="0.000008"/>
        </inertial>
    </link>

    <joint name="encoder_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="encoder_right_wheel"/>
        <origin xyz="0 -${encoder_wheel_separation/2} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="encoder_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${encoder_wheel_diameter/2}" length="${encoder_wheel_width/2}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <inertial>
            <mass value="0.01"/>
            <inertia ixx="0.000007" ixy="0.0" ixz="0.0" iyy="0.000007" iyz="0.0" izz="0.000008"/>
        </inertial>
    </link>

    <!-- CASTER WHEELS -->

    <joint name="front_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_caster_wheel"/>
        <origin xyz="0.080 0 ${chassis_base_height/2 - motor_wheel_diameter/2}" rpy="${pi} 0 0"/>
    </joint>

    <link name="front_caster_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.01" length="${chassis_base_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.01" length="${chassis_base_height-2}"/>
            </geometry>
        </collision>
    </link>

    <gazebo reference="front_caster_wheel">
        <material>Gazebo/Grey</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <joint name="back_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="back_caster_wheel"/>
        <origin xyz="-0.080 0 ${chassis_base_height/2 - motor_wheel_diameter/2}" rpy="0 0 0"/>
    </joint>

    <link name="back_caster_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.01" length="${chassis_base_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.01" length="${chassis_base_height-2}"/>
            </geometry>
        </collision>
    </link>

    <gazebo reference="back_caster_wheel">
        <material>Gazebo/Grey</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>